### ISSUE TITLE
int16_t written incorrectly

### ISSUE THREAD

**Issue by david-mccann** [HEADS-project/arduino_msgpck#2]
Hi,

I believe there is an error in the implementation of msgpck_write_integer(Stream * s, int16_t i).

If i > 127 and i <= 254, the else-part is executed. But then the number is written as an int8_t, so it will be interpreted as a negative number on the other side.

It seems that there is a case-distiction missing in the else-part: If i > 127, it should be written as uint8_t, otherwise as int8_t.

Thanks

**Comment by nharrand** [comment]
Yes indeed. The mistake extended to other cases of signed integers.

Thanks for the remark.
